export type TEmojiCategoryId =
  | 'smileys'
  | 'people'
  | 'animals'
  | 'food'
  | 'travel'
  | 'activities'
  | 'objects'
  | 'symbols'
  | 'flags';

export type TEmojiCategory = {
  id: TEmojiCategoryId;
  label: string;
  icon: string;
};

export type TEmojiItem = {
  emoji: string;
  name: string;
  keywords: string[];
  category: TEmojiCategoryId;
};

type TEmojiSeed = [string, string, string?];

export const EMOJI_CATEGORIES: TEmojiCategory[] = [
  { id: 'smileys', label: 'Smileys & emotion', icon: '😀' },
  { id: 'people', label: 'People & body', icon: '👋' },
  { id: 'animals', label: 'Animals & nature', icon: '🐻' },
  { id: 'food', label: 'Food & drink', icon: '🍔' },
  { id: 'travel', label: 'Travel & places', icon: '✈️' },
  { id: 'activities', label: 'Activities', icon: '⚽' },
  { id: 'objects', label: 'Objects', icon: '💡' },
  { id: 'symbols', label: 'Symbols', icon: '💜' },
  { id: 'flags', label: 'Flags', icon: '🏳️' },
];

const seeds: Record<TEmojiCategoryId, TEmojiSeed[]> = {
  smileys: [
    ['😀', 'grinning face', 'happy smile'],
    ['😃', 'grinning face with big eyes', 'happy'],
    ['😄', 'grinning face with smiling eyes', 'happy'],
    ['😁', 'beaming face', 'grin'],
    ['😆', 'grinning squinting face', 'laugh'],
    ['😅', 'grinning face with sweat', 'relief'],
    ['🤣', 'rolling on the floor laughing', 'lol rofl'],
    ['😂', 'face with tears of joy', 'lol cry laugh'],
    ['🙂', 'slightly smiling face', 'smile'],
    ['😉', 'winking face', 'wink'],
    ['😊', 'smiling face with smiling eyes', 'blush'],
    ['😇', 'smiling face with halo', 'angel'],
    ['🥰', 'smiling face with hearts', 'love'],
    ['😍', 'smiling face with heart eyes', 'love crush'],
    ['🤩', 'star-struck', 'excited'],
    ['😘', 'face blowing a kiss', 'kiss love'],
    ['😗', 'kissing face', 'kiss'],
    ['😚', 'kissing face with closed eyes', 'kiss'],
    ['🥲', 'smiling face with tear', 'touched'],
    ['😋', 'face savoring food', 'yum'],
    ['😛', 'face with tongue', 'tongue'],
    ['😜', 'winking face with tongue', 'wink'],
    ['🤪', 'zany face', 'goofy'],
    ['😝', 'squinting face with tongue', 'tongue'],
    ['🤑', 'money-mouth face', 'rich'],
    ['🤗', 'smiling face with open hands', 'hug'],
    ['🤭', 'face with hand over mouth', 'oops'],
    ['🤫', 'shushing face', 'quiet'],
    ['🤔', 'thinking face', 'hmm think'],
    ['🫡', 'saluting face', 'respect'],
    ['🤐', 'zipper-mouth face', 'secret'],
    ['😐', 'neutral face', 'meh'],
    ['😑', 'expressionless face', 'blank'],
    ['😶', 'face without mouth', 'silent'],
    ['😏', 'smirking face', 'smirk'],
    ['😒', 'unamused face', 'meh'],
    ['🙄', 'face with rolling eyes', 'eyeroll'],
    ['😬', 'grimacing face', 'awkward'],
    ['😴', 'sleeping face', 'sleep tired'],
    ['🤤', 'drooling face', 'hungry'],
    ['😪', 'sleepy face', 'tired'],
    ['😵', 'dizzy face', 'dead'],
    ['🤯', 'exploding head', 'mindblown'],
    ['🥳', 'partying face', 'party celebrate'],
    ['😎', 'smiling face with sunglasses', 'cool'],
    ['🤓', 'nerd face', 'geek'],
    ['🧐', 'face with monocle', 'inspect'],
    ['😕', 'confused face', 'confused'],
    ['😟', 'worried face', 'worry'],
    ['🙁', 'slightly frowning face', 'sad'],
    ['😮', 'face with open mouth', 'wow'],
    ['😯', 'hushed face', 'surprise'],
    ['😲', 'astonished face', 'shock'],
    ['😳', 'flushed face', 'embarrassed'],
    ['🥺', 'pleading face', 'please puppy'],
    ['😢', 'crying face', 'sad tear'],
    ['😭', 'loudly crying face', 'sob'],
    ['😤', 'face with steam', 'angry huff'],
    ['😠', 'angry face', 'mad'],
    ['😡', 'enraged face', 'rage'],
    ['🤬', 'face with symbols', 'swear'],
    ['😈', 'smiling face with horns', 'devil'],
    ['👿', 'angry face with horns', 'devil'],
    ['💀', 'skull', 'dead'],
    ['☠️', 'skull and crossbones', 'danger'],
    ['💩', 'pile of poo', 'poop'],
    ['🤡', 'clown face', 'clown'],
    ['👻', 'ghost', 'halloween'],
    ['👽', 'alien', 'ufo'],
    ['👾', 'alien monster', 'game'],
    ['🤖', 'robot', 'bot'],
    ['🎃', 'jack-o-lantern', 'halloween'],
    ['😺', 'grinning cat', 'cat'],
    ['😸', 'grinning cat with smiling eyes', 'cat'],
    ['😹', 'cat with tears of joy', 'cat'],
    ['😻', 'smiling cat with heart eyes', 'cat love'],
    ['😼', 'cat with wry smile', 'cat'],
    ['😽', 'kissing cat', 'cat'],
    ['🙀', 'weary cat', 'cat'],
    ['😿', 'crying cat', 'cat sad'],
    ['😾', 'pouting cat', 'cat'],
    ['🙈', 'see-no-evil monkey', 'monkey'],
    ['🙉', 'hear-no-evil monkey', 'monkey'],
    ['🙊', 'speak-no-evil monkey', 'monkey'],
    ['💋', 'kiss mark', 'lips'],
    ['💌', 'love letter', 'mail'],
    ['💘', 'heart with arrow', 'love'],
    ['💝', 'heart with ribbon', 'gift'],
    ['💖', 'sparkling heart', 'love'],
    ['💗', 'growing heart', 'love'],
    ['💓', 'beating heart', 'love'],
    ['💞', 'revolving hearts', 'love'],
    ['💕', 'two hearts', 'love'],
    ['💟', 'heart decoration', 'love'],
    ['❤️', 'red heart', 'love heart'],
    ['🧡', 'orange heart', 'love'],
    ['💛', 'yellow heart', 'love'],
    ['💚', 'green heart', 'love'],
    ['💙', 'blue heart', 'love'],
    ['💜', 'purple heart', 'love'],
    ['🖤', 'black heart', 'love'],
    ['🤍', 'white heart', 'love'],
    ['🤎', 'brown heart', 'love'],
    ['💔', 'broken heart', 'sad'],
    ['💯', 'hundred points', '100 perfect'],
    ['💥', 'collision', 'boom'],
    ['💫', 'dizzy', 'star'],
    ['💦', 'sweat droplets', 'water'],
    ['💨', 'dashing away', 'fast'],
    ['🎉', 'party popper', 'celebrate tada'],
    ['🎊', 'confetti ball', 'party'],
  ],
  people: [
    ['👋', 'waving hand', 'hello hi bye'],
    ['🤚', 'raised back of hand', 'hand'],
    ['🖐️', 'hand with fingers splayed', 'hand'],
    ['✋', 'raised hand', 'stop'],
    ['🖖', 'vulcan salute', 'star trek'],
    ['👌', 'ok hand', 'ok'],
    ['🤌', 'pinched fingers', 'italian'],
    ['🤏', 'pinching hand', 'small'],
    ['✌️', 'victory hand', 'peace'],
    ['🤞', 'crossed fingers', 'luck'],
    ['🤟', 'love-you gesture', 'love'],
    ['🤘', 'sign of the horns', 'rock'],
    ['🤙', 'call me hand', 'phone'],
    ['👈', 'backhand index pointing left', 'left'],
    ['👉', 'backhand index pointing right', 'right'],
    ['👆', 'backhand index pointing up', 'up'],
    ['👇', 'backhand index pointing down', 'down'],
    ['☝️', 'index pointing up', 'up'],
    ['👍', 'thumbs up', 'yes like'],
    ['👎', 'thumbs down', 'no dislike'],
    ['✊', 'raised fist', 'power'],
    ['👊', 'oncoming fist', 'punch'],
    ['🤛', 'left-facing fist', 'fist'],
    ['🤜', 'right-facing fist', 'fist'],
    ['👏', 'clapping hands', 'bravo clap'],
    ['🙌', 'raising hands', 'hooray'],
    ['🫶', 'heart hands', 'love'],
    ['👐', 'open hands', 'hands'],
    ['🤲', 'palms up together', 'pray'],
    ['🤝', 'handshake', 'deal'],
    ['🙏', 'folded hands', 'please thanks pray'],
    ['✍️', 'writing hand', 'write'],
    ['💅', 'nail polish', 'nails'],
    ['🤳', 'selfie', 'phone'],
    ['💪', 'flexed biceps', 'strong'],
    ['🦾', 'mechanical arm', 'robot'],
    ['🦵', 'leg', 'kick'],
    ['🦶', 'foot', 'kick'],
    ['👂', 'ear', 'listen'],
    ['👃', 'nose', 'smell'],
    ['🧠', 'brain', 'smart'],
    ['👀', 'eyes', 'look'],
    ['👁️', 'eye', 'see'],
    ['👅', 'tongue', 'taste'],
    ['👄', 'mouth', 'lips'],
    ['👶', 'baby', 'infant'],
    ['👧', 'girl', 'child'],
    ['👦', 'boy', 'child'],
    ['👩', 'woman', 'female'],
    ['👨', 'man', 'male'],
    ['👱', 'person blond hair', 'blond'],
    ['👴', 'old man', 'grandpa'],
    ['👵', 'old woman', 'grandma'],
    ['🙍', 'person frowning', 'sad'],
    ['🙎', 'person pouting', 'upset'],
    ['🙅', 'person gesturing no', 'no'],
    ['🙆', 'person gesturing ok', 'ok'],
    ['💁', 'person tipping hand', 'sassy'],
    ['🙋', 'person raising hand', 'question'],
    ['🧏', 'deaf person', 'deaf'],
    ['🙇', 'person bowing', 'sorry'],
    ['🤦', 'person facepalming', 'facepalm'],
    ['🤷', 'person shrugging', 'shrug idk'],
    ['👮', 'police officer', 'cop'],
    ['🕵️', 'detective', 'spy'],
    ['💂', 'guard', 'britain'],
    ['🥷', 'ninja', 'stealth'],
    ['👷', 'construction worker', 'build'],
    ['🤴', 'prince', 'royal'],
    ['👸', 'princess', 'royal'],
    ['👳', 'person wearing turban', 'turban'],
    ['👲', 'person with skullcap', 'hat'],
    ['🧕', 'woman with headscarf', 'hijab'],
    ['🤵', 'person in tuxedo', 'groom'],
    ['👰', 'person with veil', 'bride'],
    ['🤰', 'pregnant woman', 'baby'],
    ['🤱', 'breast-feeding', 'baby'],
    ['👼', 'baby angel', 'cherub'],
    ['🎅', 'santa claus', 'christmas'],
    ['🤶', 'mrs claus', 'christmas'],
    ['🦸', 'superhero', 'hero'],
    ['🦹', 'supervillain', 'villain'],
    ['🧙', 'mage', 'wizard'],
    ['🧚', 'fairy', 'magic'],
    ['🧛', 'vampire', 'dracula'],
    ['🧜', 'merperson', 'mermaid'],
    ['🧝', 'elf', 'fantasy'],
    ['🧞', 'genie', 'wish'],
    ['🧟', 'zombie', 'undead'],
    ['💆', 'person getting massage', 'spa'],
    ['💇', 'person getting haircut', 'salon'],
    ['🚶', 'person walking', 'walk'],
    ['🧍', 'person standing', 'stand'],
    ['🧎', 'person kneeling', 'kneel'],
    ['🏃', 'person running', 'run'],
    ['💃', 'woman dancing', 'dance'],
    ['🕺', 'man dancing', 'dance'],
    ['🕴️', 'person in suit levitating', 'hover'],
    ['👯', 'people with bunny ears', 'party'],
    ['🧖', 'person in steamy room', 'sauna'],
    ['🧗', 'person climbing', 'climb'],
    ['🤺', 'person fencing', 'sword'],
    ['🏇', 'horse racing', 'jockey'],
    ['⛷️', 'skier', 'ski'],
    ['🏂', 'snowboarder', 'snow'],
    ['🏌️', 'person golfing', 'golf'],
    ['🏄', 'person surfing', 'surf'],
    ['🚣', 'person rowing boat', 'row'],
    ['🏊', 'person swimming', 'swim'],
    ['⛹️', 'person bouncing ball', 'basketball'],
    ['🏋️', 'person lifting weights', 'gym'],
    ['🚴', 'person biking', 'bike'],
    ['🚵', 'person mountain biking', 'bike'],
    ['🤸', 'person cartwheeling', 'gymnast'],
    ['🤼', 'people wrestling', 'wrestle'],
    ['🤽', 'person playing water polo', 'polo'],
    ['🤾', 'person playing handball', 'handball'],
    ['🤹', 'person juggling', 'juggle'],
    ['🧘', 'person in lotus position', 'yoga'],
    ['🛀', 'person taking bath', 'bath'],
    ['🛌', 'person in bed', 'sleep'],
    ['👭', 'women holding hands', 'friends'],
    ['👫', 'woman and man holding hands', 'couple'],
    ['👬', 'men holding hands', 'friends'],
    ['💏', 'kiss', 'couple'],
    ['💑', 'couple with heart', 'love'],
    ['👪', 'family', 'parents'],
    ['🗣️', 'speaking head', 'talk'],
    ['👤', 'bust in silhouette', 'user'],
    ['👥', 'busts in silhouette', 'users'],
    ['🫂', 'people hugging', 'hug'],
  ],
  animals: [
    ['🐶', 'dog face', 'puppy pet'],
    ['🐕', 'dog', 'pet'],
    ['🦮', 'guide dog', 'service'],
    ['🐩', 'poodle', 'dog'],
    ['🐺', 'wolf', 'howl'],
    ['🦊', 'fox', 'animal'],
    ['🦝', 'raccoon', 'animal'],
    ['🐱', 'cat face', 'kitten pet'],
    ['🐈', 'cat', 'pet'],
    ['🦁', 'lion', 'king'],
    ['🐯', 'tiger face', 'tiger'],
    ['🐅', 'tiger', 'wild'],
    ['🐆', 'leopard', 'spots'],
    ['🐴', 'horse face', 'horse'],
    ['🐎', 'horse', 'race'],
    ['🦄', 'unicorn', 'magic'],
    ['🦓', 'zebra', 'stripes'],
    ['🦌', 'deer', 'antlers'],
    ['🐮', 'cow face', 'moo'],
    ['🐂', 'ox', 'bull'],
    ['🐃', 'water buffalo', 'buffalo'],
    ['🐄', 'cow', 'farm'],
    ['🐷', 'pig face', 'oink'],
    ['🐖', 'pig', 'farm'],
    ['🐗', 'boar', 'wild'],
    ['🐽', 'pig nose', 'snout'],
    ['🐏', 'ram', 'sheep'],
    ['🐑', 'ewe', 'sheep'],
    ['🐐', 'goat', 'farm'],
    ['🐪', 'camel', 'desert'],
    ['🐫', 'two-hump camel', 'desert'],
    ['🦙', 'llama', 'alpaca'],
    ['🦒', 'giraffe', 'tall'],
    ['🐘', 'elephant', 'trunk'],
    ['🦣', 'mammoth', 'extinct'],
    ['🦏', 'rhinoceros', 'rhino'],
    ['🦛', 'hippopotamus', 'hippo'],
    ['🐭', 'mouse face', 'mouse'],
    ['🐁', 'mouse', 'rodent'],
    ['🐀', 'rat', 'rodent'],
    ['🐹', 'hamster', 'pet'],
    ['🐰', 'rabbit face', 'bunny'],
    ['🐇', 'rabbit', 'bunny'],
    ['🐿️', 'chipmunk', 'squirrel'],
    ['🦫', 'beaver', 'dam'],
    ['🦔', 'hedgehog', 'spiky'],
    ['🦇', 'bat', 'night'],
    ['🐻', 'bear', 'animal'],
    ['🐨', 'koala', 'australia'],
    ['🐼', 'panda', 'bear'],
    ['🦥', 'sloth', 'slow'],
    ['🦦', 'otter', 'swim'],
    ['🦨', 'skunk', 'smell'],
    ['🦘', 'kangaroo', 'jump'],
    ['🦡', 'badger', 'animal'],
    ['🐾', 'paw prints', 'tracks'],
    ['🦃', 'turkey', 'thanksgiving'],
    ['🐔', 'chicken', 'hen'],
    ['🐓', 'rooster', 'bird'],
    ['🐣', 'hatching chick', 'baby'],
    ['🐤', 'baby chick', 'bird'],
    ['🐥', 'front-facing baby chick', 'bird'],
    ['🐦', 'bird', 'tweet'],
    ['🐧', 'penguin', 'cold'],
    ['🕊️', 'dove', 'peace'],
    ['🦅', 'eagle', 'bird'],
    ['🦆', 'duck', 'bird'],
    ['🦢', 'swan', 'bird'],
    ['🦉', 'owl', 'wise'],
    ['🦤', 'dodo', 'extinct'],
    ['🪶', 'feather', 'bird'],
    ['🦩', 'flamingo', 'pink'],
    ['🦚', 'peacock', 'bird'],
    ['🦜', 'parrot', 'talk'],
    ['🐸', 'frog', 'toad'],
    ['🐊', 'crocodile', 'alligator'],
    ['🐢', 'turtle', 'slow'],
    ['🦎', 'lizard', 'reptile'],
    ['🐍', 'snake', 'serpent'],
    ['🐲', 'dragon face', 'myth'],
    ['🐉', 'dragon', 'myth'],
    ['🦕', 'sauropod', 'dino'],
    ['🦖', 't-rex', 'dino'],
    ['🐳', 'spouting whale', 'ocean'],
    ['🐋', 'whale', 'ocean'],
    ['🐬', 'dolphin', 'ocean'],
    ['🦭', 'seal', 'ocean'],
    ['🐟', 'fish', 'sea'],
    ['🐠', 'tropical fish', 'sea'],
    ['🐡', 'blowfish', 'sea'],
    ['🦈', 'shark', 'ocean'],
    ['🐙', 'octopus', 'sea'],
    ['🐚', 'spiral shell', 'beach'],
    ['🪸', 'coral', 'reef'],
    ['🐌', 'snail', 'slow'],
    ['🦋', 'butterfly', 'insect'],
    ['🐛', 'bug', 'insect'],
    ['🐜', 'ant', 'insect'],
    ['🐝', 'honeybee', 'bee'],
    ['🪲', 'beetle', 'insect'],
    ['🐞', 'lady beetle', 'ladybug'],
    ['🦗', 'cricket', 'insect'],
    ['🪳', 'cockroach', 'bug'],
    ['🕷️', 'spider', 'insect'],
    ['🕸️', 'spider web', 'web'],
    ['🦂', 'scorpion', 'sting'],
    ['🦟', 'mosquito', 'bug'],
    ['🪰', 'fly', 'bug'],
    ['🪱', 'worm', 'earth'],
    ['🦠', 'microbe', 'virus germ'],
    ['💐', 'bouquet', 'flowers'],
    ['🌸', 'cherry blossom', 'flower'],
    ['💮', 'white flower', 'flower'],
    ['🏵️', 'rosette', 'flower'],
    ['🌹', 'rose', 'flower love'],
    ['🥀', 'wilted flower', 'sad'],
    ['🌺', 'hibiscus', 'flower'],
    ['🌻', 'sunflower', 'flower'],
    ['🌼', 'blossom', 'flower'],
    ['🌷', 'tulip', 'flower'],
    ['🌱', 'seedling', 'plant'],
    ['🪴', 'potted plant', 'plant'],
    ['🌲', 'evergreen tree', 'tree'],
    ['🌳', 'deciduous tree', 'tree'],
    ['🌴', 'palm tree', 'tropical'],
    ['🌵', 'cactus', 'desert'],
    ['🌾', 'sheaf of rice', 'grain'],
    ['🌿', 'herb', 'leaf'],
    ['☘️', 'shamrock', 'luck'],
    ['🍀', 'four leaf clover', 'luck'],
    ['🍁', 'maple leaf', 'fall'],
    ['🍂', 'fallen leaf', 'autumn'],
    ['🍃', 'leaf fluttering', 'wind'],
    ['🍄', 'mushroom', 'fungus'],
  ],
  food: [
    ['🍇', 'grapes', 'fruit'],
    ['🍈', 'melon', 'fruit'],
    ['🍉', 'watermelon', 'fruit'],
    ['🍊', 'tangerine', 'orange fruit'],
    ['🍋', 'lemon', 'fruit'],
    ['🍌', 'banana', 'fruit'],
    ['🍍', 'pineapple', 'fruit'],
    ['🥭', 'mango', 'fruit'],
    ['🍎', 'red apple', 'fruit'],
    ['🍏', 'green apple', 'fruit'],
    ['🍐', 'pear', 'fruit'],
    ['🍑', 'peach', 'fruit'],
    ['🍒', 'cherries', 'fruit'],
    ['🍓', 'strawberry', 'fruit'],
    ['🫐', 'blueberries', 'fruit'],
    ['🥝', 'kiwi fruit', 'fruit'],
    ['🍅', 'tomato', 'veg'],
    ['🫒', 'olive', 'food'],
    ['🥥', 'coconut', 'fruit'],
    ['🥑', 'avocado', 'food'],
    ['🍆', 'eggplant', 'veg'],
    ['🥔', 'potato', 'veg'],
    ['🥕', 'carrot', 'veg'],
    ['🌽', 'ear of corn', 'veg'],
    ['🌶️', 'hot pepper', 'spicy'],
    ['🫑', 'bell pepper', 'veg'],
    ['🥒', 'cucumber', 'veg'],
    ['🥬', 'leafy green', 'salad'],
    ['🥦', 'broccoli', 'veg'],
    ['🧄', 'garlic', 'food'],
    ['🧅', 'onion', 'food'],
    ['🥜', 'peanuts', 'nut'],
    ['🫘', 'beans', 'food'],
    ['🌰', 'chestnut', 'nut'],
    ['🍞', 'bread', 'toast'],
    ['🥐', 'croissant', 'bakery'],
    ['🥖', 'baguette', 'bread'],
    ['🫓', 'flatbread', 'bread'],
    ['🥨', 'pretzel', 'snack'],
    ['🥯', 'bagel', 'bread'],
    ['🥞', 'pancakes', 'breakfast'],
    ['🧇', 'waffle', 'breakfast'],
    ['🧀', 'cheese wedge', 'cheese'],
    ['🍖', 'meat on bone', 'meat'],
    ['🍗', 'poultry leg', 'chicken'],
    ['🥩', 'cut of meat', 'steak'],
    ['🥓', 'bacon', 'breakfast'],
    ['🍔', 'hamburger', 'burger'],
    ['🍟', 'french fries', 'fries'],
    ['🍕', 'pizza', 'slice'],
    ['🌭', 'hot dog', 'food'],
    ['🥪', 'sandwich', 'lunch'],
    ['🌮', 'taco', 'mexican'],
    ['🌯', 'burrito', 'mexican'],
    ['🫔', 'tamale', 'mexican'],
    ['🥙', 'stuffed flatbread', 'gyro'],
    ['🧆', 'falafel', 'food'],
    ['🥚', 'egg', 'breakfast'],
    ['🍳', 'cooking', 'fried egg'],
    ['🥘', 'shallow pan of food', 'paella'],
    ['🍲', 'pot of food', 'stew'],
    ['🫕', 'fondue', 'cheese'],
    ['🥣', 'bowl with spoon', 'cereal'],
    ['🥗', 'green salad', 'healthy'],
    ['🍿', 'popcorn', 'movie'],
    ['🧈', 'butter', 'food'],
    ['🧂', 'salt', 'season'],
    ['🥫', 'canned food', 'can'],
    ['🍱', 'bento box', 'lunch'],
    ['🍘', 'rice cracker', 'snack'],
    ['🍙', 'rice ball', 'onigiri'],
    ['🍚', 'cooked rice', 'rice'],
    ['🍛', 'curry rice', 'curry'],
    ['🍜', 'steaming bowl', 'ramen'],
    ['🍝', 'spaghetti', 'pasta'],
    ['🍠', 'roasted sweet potato', 'food'],
    ['🍢', 'oden', 'skewer'],
    ['🍣', 'sushi', 'japan'],
    ['🍤', 'fried shrimp', 'tempura'],
    ['🍥', 'fish cake', 'naruto'],
    ['🥮', 'moon cake', 'festival'],
    ['🍡', 'dango', 'skewer'],
    ['🥟', 'dumpling', 'gyoza'],
    ['🥠', 'fortune cookie', 'luck'],
    ['🥡', 'takeout box', 'chinese'],
    ['🦀', 'crab', 'seafood'],
    ['🦞', 'lobster', 'seafood'],
    ['🦐', 'shrimp', 'seafood'],
    ['🦑', 'squid', 'seafood'],
    ['🦪', 'oyster', 'seafood'],
    ['🍦', 'soft ice cream', 'dessert'],
    ['🍧', 'shaved ice', 'dessert'],
    ['🍨', 'ice cream', 'dessert'],
    ['🍩', 'doughnut', 'donut'],
    ['🍪', 'cookie', 'dessert'],
    ['🎂', 'birthday cake', 'party'],
    ['🍰', 'shortcake', 'dessert'],
    ['🧁', 'cupcake', 'dessert'],
    ['🥧', 'pie', 'dessert'],
    ['🍫', 'chocolate bar', 'candy'],
    ['🍬', 'candy', 'sweet'],
    ['🍭', 'lollipop', 'candy'],
    ['🍮', 'custard', 'pudding'],
    ['🍯', 'honey pot', 'sweet'],
    ['🍼', 'baby bottle', 'milk'],
    ['🥛', 'glass of milk', 'drink'],
    ['☕', 'hot beverage', 'coffee tea'],
    ['🫖', 'teapot', 'tea'],
    ['🍵', 'teacup without handle', 'tea'],
    ['🍶', 'sake', 'japan'],
    ['🍾', 'bottle with popping cork', 'champagne'],
    ['🍷', 'wine glass', 'drink'],
    ['🍸', 'cocktail glass', 'drink'],
    ['🍹', 'tropical drink', 'cocktail'],
    ['🍺', 'beer mug', 'drink'],
    ['🍻', 'clinking beer mugs', 'cheers'],
    ['🥂', 'clinking glasses', 'cheers'],
    ['🥃', 'tumbler glass', 'whiskey'],
    ['🥤', 'cup with straw', 'soda'],
    ['🧋', 'bubble tea', 'boba'],
    ['🧃', 'beverage box', 'juice'],
    ['🧉', 'mate', 'drink'],
    ['🧊', 'ice', 'cold'],
    ['🥢', 'chopsticks', 'utensil'],
    ['🍽️', 'fork and knife with plate', 'dinner'],
    ['🍴', 'fork and knife', 'eat'],
    ['🥄', 'spoon', 'utensil'],
  ],
  travel: [
    ['🌍', 'globe europe africa', 'world'],
    ['🌎', 'globe americas', 'world'],
    ['🌏', 'globe asia australia', 'world'],
    ['🌐', 'globe with meridians', 'internet'],
    ['🗺️', 'world map', 'map'],
    ['🗾', 'map of japan', 'japan'],
    ['🧭', 'compass', 'navigate'],
    ['🏔️', 'snow-capped mountain', 'alps'],
    ['⛰️', 'mountain', 'hike'],
    ['🌋', 'volcano', 'erupt'],
    ['🗻', 'mount fuji', 'japan'],
    ['🏕️', 'camping', 'tent'],
    ['🏖️', 'beach with umbrella', 'vacation'],
    ['🏜️', 'desert', 'sand'],
    ['🏝️', 'desert island', 'tropical'],
    ['🏞️', 'national park', 'nature'],
    ['🏟️', 'stadium', 'sport'],
    ['🏛️', 'classical building', 'museum'],
    ['🏗️', 'building construction', 'crane'],
    ['🧱', 'brick', 'wall'],
    ['🏘️', 'houses', 'neighborhood'],
    ['🏚️', 'derelict house', 'abandoned'],
    ['🏠', 'house', 'home'],
    ['🏡', 'house with garden', 'home'],
    ['🏢', 'office building', 'work'],
    ['🏣', 'japanese post office', 'mail'],
    ['🏤', 'post office', 'mail'],
    ['🏥', 'hospital', 'health'],
    ['🏦', 'bank', 'money'],
    ['🏨', 'hotel', 'stay'],
    ['🏩', 'love hotel', 'stay'],
    ['🏪', 'convenience store', 'shop'],
    ['🏫', 'school', 'education'],
    ['🏬', 'department store', 'shop'],
    ['🏭', 'factory', 'industry'],
    ['🏯', 'japanese castle', 'japan'],
    ['🏰', 'castle', 'fairytale'],
    ['💒', 'wedding', 'church'],
    ['🗼', 'tokyo tower', 'japan'],
    ['🗽', 'statue of liberty', 'nyc'],
    ['⛪', 'church', 'religion'],
    ['🕌', 'mosque', 'islam'],
    ['🛕', 'hindu temple', 'temple'],
    ['🕍', 'synagogue', 'jewish'],
    ['⛩️', 'shinto shrine', 'japan'],
    ['🕋', 'kaaba', 'mecca'],
    ['⛲', 'fountain', 'park'],
    ['⛺', 'tent', 'camp'],
    ['🌁', 'foggy', 'mist'],
    ['🌃', 'night with stars', 'city'],
    ['🏙️', 'cityscape', 'skyline'],
    ['🌄', 'sunrise over mountains', 'dawn'],
    ['🌅', 'sunrise', 'morning'],
    ['🌆', 'cityscape at dusk', 'sunset'],
    ['🌇', 'sunset', 'dusk'],
    ['🌉', 'bridge at night', 'city'],
    ['♨️', 'hot springs', 'onsen'],
    ['🎠', 'carousel horse', 'fair'],
    ['🎡', 'ferris wheel', 'fair'],
    ['🎢', 'roller coaster', 'park'],
    ['💈', 'barber pole', 'hair'],
    ['🎪', 'circus tent', 'show'],
    ['🚂', 'locomotive', 'train'],
    ['🚃', 'railway car', 'train'],
    ['🚄', 'high-speed train', 'shinkansen'],
    ['🚅', 'bullet train', 'japan'],
    ['🚆', 'train', 'rail'],
    ['🚇', 'metro', 'subway'],
    ['🚈', 'light rail', 'tram'],
    ['🚉', 'station', 'train'],
    ['🚊', 'tram', 'streetcar'],
    ['🚝', 'monorail', 'train'],
    ['🚞', 'mountain railway', 'train'],
    ['🚋', 'tram car', 'streetcar'],
    ['🚌', 'bus', 'transit'],
    ['🚍', 'oncoming bus', 'transit'],
    ['🚎', 'trolleybus', 'transit'],
    ['🚐', 'minibus', 'van'],
    ['🚑', 'ambulance', 'emergency'],
    ['🚒', 'fire engine', 'emergency'],
    ['🚓', 'police car', 'cop'],
    ['🚔', 'oncoming police car', 'cop'],
    ['🚕', 'taxi', 'cab'],
    ['🚖', 'oncoming taxi', 'cab'],
    ['🚗', 'automobile', 'car'],
    ['🚘', 'oncoming automobile', 'car'],
    ['🚙', 'sport utility vehicle', 'suv'],
    ['🛻', 'pickup truck', 'truck'],
    ['🚚', 'delivery truck', 'shipping'],
    ['🚛', 'articulated lorry', 'truck'],
    ['🚜', 'tractor', 'farm'],
    ['🏎️', 'racing car', 'fast'],
    ['🏍️', 'motorcycle', 'bike'],
    ['🛵', 'motor scooter', 'vespa'],
    ['🦽', 'manual wheelchair', 'access'],
    ['🦼', 'motorized wheelchair', 'access'],
    ['🛺', 'auto rickshaw', 'tuk tuk'],
    ['🚲', 'bicycle', 'bike'],
    ['🛴', 'kick scooter', 'ride'],
    ['🛹', 'skateboard', 'skate'],
    ['🛼', 'roller skate', 'skate'],
    ['🚏', 'bus stop', 'transit'],
    ['🛣️', 'motorway', 'highway'],
    ['🛤️', 'railway track', 'train'],
    ['🛢️', 'oil drum', 'fuel'],
    ['⛽', 'fuel pump', 'gas'],
    ['🚨', 'police car light', 'alert'],
    ['🚥', 'horizontal traffic light', 'stop'],
    ['🚦', 'vertical traffic light', 'stop'],
    ['🛑', 'stop sign', 'stop'],
    ['🚧', 'construction', 'work'],
    ['⚓', 'anchor', 'ship'],
    ['⛵', 'sailboat', 'boat'],
    ['🛶', 'canoe', 'boat'],
    ['🚤', 'speedboat', 'boat'],
    ['🛳️', 'passenger ship', 'cruise'],
    ['⛴️', 'ferry', 'boat'],
    ['🛥️', 'motor boat', 'boat'],
    ['🚢', 'ship', 'boat'],
    ['✈️', 'airplane', 'flight travel'],
    ['🛩️', 'small airplane', 'flight'],
    ['🛫', 'airplane departure', 'takeoff'],
    ['🛬', 'airplane arrival', 'landing'],
    ['🪂', 'parachute', 'sky'],
    ['💺', 'seat', 'plane'],
    ['🚁', 'helicopter', 'flight'],
    ['🚟', 'suspension railway', 'train'],
    ['🚠', 'mountain cableway', 'gondola'],
    ['🚡', 'aerial tramway', 'cable'],
    ['🛰️', 'satellite', 'space'],
    ['🚀', 'rocket', 'space launch'],
    ['🛸', 'flying saucer', 'ufo'],
    ['🛎️', 'bellhop bell', 'hotel'],
    ['🧳', 'luggage', 'travel bag'],
    ['⌛', 'hourglass done', 'time'],
    ['⏳', 'hourglass not done', 'wait'],
    ['⌚', 'watch', 'time'],
    ['⏰', 'alarm clock', 'wake'],
    ['⏱️', 'stopwatch', 'timer'],
    ['⏲️', 'timer clock', 'timer'],
    ['🕰️', 'mantelpiece clock', 'time'],
    ['🕛', 'twelve o’clock', 'noon'],
    ['🌙', 'crescent moon', 'night'],
    ['🌚', 'new moon face', 'moon'],
    ['🌛', 'first quarter moon face', 'moon'],
    ['🌜', 'last quarter moon face', 'moon'],
    ['🌝', 'full moon face', 'moon'],
    ['🌞', 'sun with face', 'sun'],
    ['⭐', 'star', 'night'],
    ['🌟', 'glowing star', 'shine'],
    ['🌠', 'shooting star', 'wish'],
    ['🌌', 'milky way', 'space'],
    ['☁️', 'cloud', 'weather'],
    ['⛅', 'sun behind cloud', 'weather'],
    ['⛈️', 'cloud with lightning and rain', 'storm'],
    ['🌤️', 'sun behind small cloud', 'weather'],
    ['🌧️', 'cloud with rain', 'rain'],
    ['🌨️', 'cloud with snow', 'snow'],
    ['🌩️', 'cloud with lightning', 'storm'],
    ['🌪️', 'tornado', 'storm'],
    ['🌫️', 'fog', 'weather'],
    ['🌬️', 'wind face', 'blow'],
    ['🌀', 'cyclone', 'typhoon'],
    ['🌈', 'rainbow', 'pride'],
    ['🌂', 'closed umbrella', 'rain'],
    ['☂️', 'umbrella', 'rain'],
    ['☔', 'umbrella with rain drops', 'rain'],
    ['⛱️', 'umbrella on ground', 'beach'],
    ['⚡', 'high voltage', 'zap lightning'],
    ['❄️', 'snowflake', 'cold'],
    ['☃️', 'snowman', 'winter'],
    ['⛄', 'snowman without snow', 'winter'],
    ['☄️', 'comet', 'space'],
    ['🔥', 'fire', 'hot flame'],
    ['💧', 'droplet', 'water'],
    ['🌊', 'water wave', 'ocean'],
  ],
  activities: [
    ['🎃', 'jack-o-lantern', 'halloween'],
    ['🎄', 'christmas tree', 'holiday'],
    ['🎆', 'fireworks', 'celebrate'],
    ['🎇', 'sparkler', 'celebrate'],
    ['🧨', 'firecracker', 'boom'],
    ['✨', 'sparkles', 'shine'],
    ['🎈', 'balloon', 'party'],
    ['🎉', 'party popper', 'tada'],
    ['🎊', 'confetti ball', 'party'],
    ['🎋', 'tanabata tree', 'wish'],
    ['🎍', 'pine decoration', 'new year'],
    ['🎎', 'japanese dolls', 'festival'],
    ['🎏', 'carp streamer', 'japan'],
    ['🎐', 'wind chime', 'summer'],
    ['🎑', 'moon viewing ceremony', 'festival'],
    ['🧧', 'red envelope', 'luck'],
    ['🎀', 'ribbon', 'gift'],
    ['🎁', 'wrapped gift', 'present'],
    ['🎗️', 'reminder ribbon', 'awareness'],
    ['🎟️', 'admission tickets', 'event'],
    ['🎫', 'ticket', 'event'],
    ['🎖️', 'military medal', 'award'],
    ['🏆', 'trophy', 'win'],
    ['🏅', 'sports medal', 'award'],
    ['🥇', '1st place medal', 'gold'],
    ['🥈', '2nd place medal', 'silver'],
    ['🥉', '3rd place medal', 'bronze'],
    ['⚽', 'soccer ball', 'football'],
    ['⚾', 'baseball', 'sport'],
    ['🥎', 'softball', 'sport'],
    ['🏀', 'basketball', 'sport'],
    ['🏐', 'volleyball', 'sport'],
    ['🏈', 'american football', 'sport'],
    ['🏉', 'rugby football', 'sport'],
    ['🎾', 'tennis', 'sport'],
    ['🥏', 'flying disc', 'frisbee'],
    ['🎳', 'bowling', 'sport'],
    ['🏏', 'cricket game', 'sport'],
    ['🏑', 'field hockey', 'sport'],
    ['🏒', 'ice hockey', 'sport'],
    ['🥍', 'lacrosse', 'sport'],
    ['🏓', 'ping pong', 'sport'],
    ['🏸', 'badminton', 'sport'],
    ['🥊', 'boxing glove', 'fight'],
    ['🥋', 'martial arts uniform', 'karate'],
    ['🥅', 'goal net', 'sport'],
    ['⛳', 'flag in hole', 'golf'],
    ['⛸️', 'ice skate', 'winter'],
    ['🎣', 'fishing pole', 'fish'],
    ['🤿', 'diving mask', 'scuba'],
    ['🎽', 'running shirt', 'marathon'],
    ['🎿', 'skis', 'snow'],
    ['🛷', 'sled', 'snow'],
    ['🥌', 'curling stone', 'sport'],
    ['🎯', 'bullseye', 'target'],
    ['🪀', 'yo-yo', 'toy'],
    ['🪁', 'kite', 'fly'],
    ['🎱', 'pool 8 ball', 'billiards'],
    ['🔮', 'crystal ball', 'fortune'],
    ['🪄', 'magic wand', 'magic'],
    ['🧿', 'nazar amulet', 'luck'],
    ['🎮', 'video game', 'controller'],
    ['🕹️', 'joystick', 'arcade'],
    ['🎰', 'slot machine', 'casino'],
    ['🎲', 'game die', 'dice'],
    ['🧩', 'puzzle piece', 'jigsaw'],
    ['🧸', 'teddy bear', 'toy'],
    ['🪅', 'piñata', 'party'],
    ['🪆', 'nesting dolls', 'matryoshka'],
    ['♠️', 'spade suit', 'cards'],
    ['♥️', 'heart suit', 'cards'],
    ['♦️', 'diamond suit', 'cards'],
    ['♣️', 'club suit', 'cards'],
    ['♟️', 'chess pawn', 'chess'],
    ['🃏', 'joker', 'cards'],
    ['🀄', 'mahjong red dragon', 'game'],
    ['🎴', 'flower playing cards', 'hanafuda'],
    ['🎭', 'performing arts', 'theater'],
    ['🖼️', 'framed picture', 'art'],
    ['🎨', 'artist palette', 'paint'],
    ['🧵', 'thread', 'sew'],
    ['🪡', 'sewing needle', 'sew'],
    ['🧶', 'yarn', 'knit'],
    ['🪢', 'knot', 'rope'],
  ],
  objects: [
    ['👓', 'glasses', 'vision'],
    ['🕶️', 'sunglasses', 'cool'],
    ['🥽', 'goggles', 'safety'],
    ['🥼', 'lab coat', 'science'],
    ['🦺', 'safety vest', 'work'],
    ['👔', 'necktie', 'shirt'],
    ['👕', 't-shirt', 'clothes'],
    ['👖', 'jeans', 'pants'],
    ['🧣', 'scarf', 'winter'],
    ['🧤', 'gloves', 'hands'],
    ['🧥', 'coat', 'jacket'],
    ['🧦', 'socks', 'feet'],
    ['👗', 'dress', 'clothes'],
    ['👘', 'kimono', 'japan'],
    ['🥻', 'sari', 'dress'],
    ['🩱', 'one-piece swimsuit', 'swim'],
    ['🩲', 'briefs', 'swim'],
    ['🩳', 'shorts', 'clothes'],
    ['👙', 'bikini', 'swim'],
    ['👚', 'woman’s clothes', 'shirt'],
    ['👛', 'purse', 'bag'],
    ['👜', 'handbag', 'bag'],
    ['👝', 'clutch bag', 'bag'],
    ['🛍️', 'shopping bags', 'shop'],
    ['🎒', 'backpack', 'school'],
    ['🩴', 'thong sandal', 'flip flop'],
    ['👞', 'man’s shoe', 'shoe'],
    ['👟', 'running shoe', 'sneaker'],
    ['🥾', 'hiking boot', 'boot'],
    ['🥿', 'flat shoe', 'ballet'],
    ['👠', 'high-heeled shoe', 'heel'],
    ['👡', 'woman’s sandal', 'shoe'],
    ['🩰', 'ballet shoes', 'dance'],
    ['👢', 'woman’s boot', 'shoe'],
    ['👑', 'crown', 'king'],
    ['👒', 'woman’s hat', 'hat'],
    ['🎩', 'top hat', 'formal'],
    ['🎓', 'graduation cap', 'school'],
    ['🧢', 'billed cap', 'hat'],
    ['🪖', 'military helmet', 'army'],
    ['⛑️', 'rescue worker’s helmet', 'help'],
    ['📿', 'prayer beads', 'religion'],
    ['💄', 'lipstick', 'makeup'],
    ['💍', 'ring', 'wedding'],
    ['💎', 'gem stone', 'diamond'],
    ['🔇', 'muted speaker', 'sound off'],
    ['🔈', 'speaker low volume', 'sound'],
    ['🔉', 'speaker medium volume', 'sound'],
    ['🔊', 'speaker high volume', 'loud'],
    ['📢', 'loudspeaker', 'announce'],
    ['📣', 'megaphone', 'cheer'],
    ['📯', 'postal horn', 'mail'],
    ['🔔', 'bell', 'notify'],
    ['🔕', 'bell with slash', 'mute'],
    ['🎼', 'musical score', 'music'],
    ['🎵', 'musical note', 'music'],
    ['🎶', 'musical notes', 'music'],
    ['🎙️', 'studio microphone', 'podcast'],
    ['🎚️', 'level slider', 'audio'],
    ['🎛️', 'control knobs', 'mix'],
    ['🎤', 'microphone', 'sing'],
    ['🎧', 'headphone', 'music'],
    ['📻', 'radio', 'music'],
    ['🎷', 'saxophone', 'jazz'],
    ['🪗', 'accordion', 'music'],
    ['🎸', 'guitar', 'music'],
    ['🎹', 'musical keyboard', 'piano'],
    ['🎺', 'trumpet', 'brass'],
    ['🎻', 'violin', 'strings'],
    ['🪕', 'banjo', 'music'],
    ['🥁', 'drum', 'music'],
    ['🪘', 'long drum', 'music'],
    ['📱', 'mobile phone', 'iphone'],
    ['📲', 'mobile phone with arrow', 'call'],
    ['☎️', 'telephone', 'phone'],
    ['📞', 'telephone receiver', 'call'],
    ['📟', 'pager', 'beeper'],
    ['📠', 'fax machine', 'fax'],
    ['🔋', 'battery', 'power'],
    ['🔌', 'electric plug', 'power'],
    ['💻', 'laptop', 'computer'],
    ['🖥️', 'desktop computer', 'pc'],
    ['🖨️', 'printer', 'print'],
    ['⌨️', 'keyboard', 'type'],
    ['🖱️', 'computer mouse', 'click'],
    ['🖲️', 'trackball', 'mouse'],
    ['💽', 'computer disk', 'minidisc'],
    ['💾', 'floppy disk', 'save'],
    ['💿', 'optical disk', 'cd'],
    ['📀', 'dvd', 'disk'],
    ['🧮', 'abacus', 'math'],
    ['🎥', 'movie camera', 'film'],
    ['🎞️', 'film frames', 'cinema'],
    ['📽️', 'film projector', 'movie'],
    ['🎬', 'clapper board', 'action'],
    ['📺', 'television', 'tv'],
    ['📷', 'camera', 'photo'],
    ['📸', 'camera with flash', 'photo'],
    ['📹', 'video camera', 'record'],
    ['📼', 'videocassette', 'vhs'],
    ['🔍', 'magnifying glass tilted left', 'search'],
    ['🔎', 'magnifying glass tilted right', 'search'],
    ['🕯️', 'candle', 'light'],
    ['💡', 'light bulb', 'idea'],
    ['🔦', 'flashlight', 'torch'],
    ['🏮', 'red paper lantern', 'izakaya'],
    ['🪔', 'diya lamp', 'light'],
    ['📔', 'notebook with decorative cover', 'notes'],
    ['📕', 'closed book', 'read'],
    ['📖', 'open book', 'read'],
    ['📗', 'green book', 'read'],
    ['📘', 'blue book', 'read'],
    ['📙', 'orange book', 'read'],
    ['📚', 'books', 'library'],
    ['📓', 'notebook', 'notes'],
    ['📒', 'ledger', 'notes'],
    ['📃', 'page with curl', 'document'],
    ['📜', 'scroll', 'document'],
    ['📄', 'page facing up', 'document'],
    ['📰', 'newspaper', 'news'],
    ['📓', 'notebook', 'notes'],
    ['📑', 'bookmark tabs', 'mark'],
    ['🔖', 'bookmark', 'save'],
    ['🏷️', 'label', 'tag'],
    ['💰', 'money bag', 'cash'],
    ['🪙', 'coin', 'money'],
    ['💴', 'yen banknote', 'money'],
    ['💵', 'dollar banknote', 'money'],
    ['💶', 'euro banknote', 'money'],
    ['💷', 'pound banknote', 'money'],
    ['💸', 'money with wings', 'spend'],
    ['💳', 'credit card', 'pay'],
    ['🧾', 'receipt', 'bill'],
    ['💹', 'chart increasing with yen', 'stocks'],
    ['✉️', 'envelope', 'mail'],
    ['📧', 'e-mail', 'mail'],
    ['📨', 'incoming envelope', 'mail'],
    ['📩', 'envelope with arrow', 'send'],
    ['📤', 'outbox tray', 'send'],
    ['📥', 'inbox tray', 'receive'],
    ['📦', 'package', 'box'],
    ['📫', 'closed mailbox with raised flag', 'mail'],
    ['📪', 'closed mailbox with lowered flag', 'mail'],
    ['📬', 'open mailbox with raised flag', 'mail'],
    ['📭', 'open mailbox with lowered flag', 'mail'],
    ['📮', 'postbox', 'mail'],
    ['🗳️', 'ballot box', 'vote'],
    ['✏️', 'pencil', 'write'],
    ['✒️', 'black nib', 'pen'],
    ['🖋️', 'fountain pen', 'write'],
    ['🖊️', 'pen', 'write'],
    ['🖌️', 'paintbrush', 'art'],
    ['🖍️', 'crayon', 'draw'],
    ['📝', 'memo', 'note'],
    ['💼', 'briefcase', 'work'],
    ['📁', 'file folder', 'directory'],
    ['📂', 'open file folder', 'directory'],
    ['🗂️', 'card index dividers', 'files'],
    ['📅', 'calendar', 'date'],
    ['📆', 'tear-off calendar', 'date'],
    ['🗒️', 'spiral notepad', 'notes'],
    ['🗓️', 'spiral calendar', 'date'],
    ['📇', 'card index', 'contacts'],
    ['📈', 'chart increasing', 'growth'],
    ['📉', 'chart decreasing', 'loss'],
    ['📊', 'bar chart', 'stats'],
    ['📋', 'clipboard', 'copy'],
    ['📌', 'pushpin', 'pin'],
    ['📍', 'round pushpin', 'location'],
    ['📎', 'paperclip', 'attach'],
    ['🖇️', 'linked paperclips', 'attach'],
    ['📏', 'straight ruler', 'measure'],
    ['📐', 'triangular ruler', 'measure'],
    ['✂️', 'scissors', 'cut'],
    ['🗃️', 'card file box', 'archive'],
    ['🗄️', 'file cabinet', 'files'],
    ['🗑️', 'wastebasket', 'trash'],
    ['🔒', 'locked', 'secure'],
    ['🔓', 'unlocked', 'open'],
    ['🔏', 'locked with pen', 'privacy'],
    ['🔐', 'locked with key', 'secure'],
    ['🔑', 'key', 'password'],
    ['🗝️', 'old key', 'unlock'],
    ['🔨', 'hammer', 'tool'],
    ['🪓', 'axe', 'chop'],
    ['⛏️', 'pick', 'mine'],
    ['⚒️', 'hammer and pick', 'tools'],
    ['🛠️', 'hammer and wrench', 'tools'],
    ['🗡️', 'dagger', 'knife'],
    ['⚔️', 'crossed swords', 'battle'],
    ['🔫', 'water pistol', 'gun'],
    ['🪃', 'boomerang', 'throw'],
    ['🏹', 'bow and arrow', 'archery'],
    ['🛡️', 'shield', 'protect'],
    ['🪚', 'carpentry saw', 'wood'],
    ['🔧', 'wrench', 'tool'],
    ['🪛', 'screwdriver', 'tool'],
    ['🔩', 'nut and bolt', 'hardware'],
    ['⚙️', 'gear', 'settings'],
    ['🗜️', 'clamp', 'tool'],
    ['⚖️', 'balance scale', 'justice'],
    ['🦯', 'white cane', 'access'],
    ['🔗', 'link', 'url'],
    ['⛓️', 'chains', 'link'],
    ['🪝', 'hook', 'catch'],
    ['🧰', 'toolbox', 'tools'],
    ['🧲', 'magnet', 'attract'],
    ['🪜', 'ladder', 'climb'],
    ['⚗️', 'alembic', 'science'],
    ['🧪', 'test tube', 'science'],
    ['🧫', 'petri dish', 'lab'],
    ['🧬', 'dna', 'science'],
    ['🔬', 'microscope', 'science'],
    ['🔭', 'telescope', 'space'],
    ['📡', 'satellite antenna', 'signal'],
    ['💉', 'syringe', 'shot'],
    ['🩸', 'drop of blood', 'health'],
    ['💊', 'pill', 'medicine'],
    ['🩹', 'adhesive bandage', 'band-aid'],
    ['🩺', 'stethoscope', 'doctor'],
    ['🚪', 'door', 'enter'],
    ['🪞', 'mirror', 'reflect'],
    ['🪟', 'window', 'view'],
    ['🛏️', 'bed', 'sleep'],
    ['🛋️', 'couch and lamp', 'sofa'],
    ['🪑', 'chair', 'sit'],
    ['🚽', 'toilet', 'bath'],
    ['🪠', 'plunger', 'bath'],
    ['🚿', 'shower', 'bath'],
    ['🛁', 'bathtub', 'bath'],
    ['🪤', 'mouse trap', 'catch'],
    ['🪒', 'razor', 'shave'],
    ['🧴', 'lotion bottle', 'soap'],
    ['🧷', 'safety pin', 'clip'],
    ['🧹', 'broom', 'clean'],
    ['🧺', 'basket', 'laundry'],
    ['🧻', 'roll of paper', 'tp'],
    ['🪣', 'bucket', 'pail'],
    ['🧼', 'soap', 'clean'],
    ['🪥', 'toothbrush', 'clean'],
    ['🧽', 'sponge', 'clean'],
    ['🧯', 'fire extinguisher', 'safety'],
    ['🛒', 'shopping cart', 'cart'],
    ['🚬', 'cigarette', 'smoke'],
    ['⚰️', 'coffin', 'dead'],
    ['🪦', 'headstone', 'grave'],
    ['⚱️', 'funeral urn', 'ashes'],
    ['🗿', 'moai', 'easter island'],
    ['🪧', 'placard', 'sign'],
  ],
  symbols: [
    ['❤️', 'red heart', 'love'],
    ['🧡', 'orange heart', 'love'],
    ['💛', 'yellow heart', 'love'],
    ['💚', 'green heart', 'love'],
    ['💙', 'blue heart', 'love'],
    ['💜', 'purple heart', 'love'],
    ['🖤', 'black heart', 'love'],
    ['🤍', 'white heart', 'love'],
    ['🤎', 'brown heart', 'love'],
    ['💔', 'broken heart', 'sad'],
    ['❣️', 'heart exclamation', 'love'],
    ['💕', 'two hearts', 'love'],
    ['💞', 'revolving hearts', 'love'],
    ['💓', 'beating heart', 'love'],
    ['💗', 'growing heart', 'love'],
    ['💖', 'sparkling heart', 'love'],
    ['💘', 'heart with arrow', 'love'],
    ['💝', 'heart with ribbon', 'gift'],
    ['💟', 'heart decoration', 'love'],
    ['☮️', 'peace symbol', 'peace'],
    ['✝️', 'latin cross', 'christian'],
    ['☪️', 'star and crescent', 'islam'],
    ['🕉️', 'om', 'hindu'],
    ['☸️', 'wheel of dharma', 'buddhist'],
    ['✡️', 'star of david', 'jewish'],
    ['🔯', 'dotted six-pointed star', 'star'],
    ['🕎', 'menorah', 'jewish'],
    ['☯️', 'yin yang', 'balance'],
    ['☦️', 'orthodox cross', 'christian'],
    ['🛐', 'place of worship', 'religion'],
    ['⛎', 'ophiuchus', 'zodiac'],
    ['♈', 'aries', 'zodiac'],
    ['♉', 'taurus', 'zodiac'],
    ['♊', 'gemini', 'zodiac'],
    ['♋', 'cancer', 'zodiac'],
    ['♌', 'leo', 'zodiac'],
    ['♍', 'virgo', 'zodiac'],
    ['♎', 'libra', 'zodiac'],
    ['♏', 'scorpio', 'zodiac'],
    ['♐', 'sagittarius', 'zodiac'],
    ['♑', 'capricorn', 'zodiac'],
    ['♒', 'aquarius', 'zodiac'],
    ['♓', 'pisces', 'zodiac'],
    ['🆔', 'id button', 'identity'],
    ['⚛️', 'atom symbol', 'science'],
    ['🉑', 'japanese acceptable button', 'ok'],
    ['☢️', 'radioactive', 'danger'],
    ['☣️', 'biohazard', 'danger'],
    ['📴', 'mobile phone off', 'mute'],
    ['📳', 'vibration mode', 'phone'],
    ['🈶', 'japanese not free of charge', 'kanji'],
    ['🈚', 'japanese free of charge', 'kanji'],
    ['🈸', 'japanese application', 'kanji'],
    ['🈺', 'japanese open for business', 'kanji'],
    ['🈷️', 'japanese monthly amount', 'kanji'],
    ['✴️', 'eight-pointed star', 'star'],
    ['🆚', 'vs button', 'versus'],
    ['💮', 'white flower', 'nice'],
    ['🉐', 'japanese bargain', 'kanji'],
    ['㊙️', 'japanese secret', 'kanji'],
    ['㊗️', 'japanese congratulations', 'kanji'],
    ['🈴', 'japanese passing grade', 'kanji'],
    ['🈵', 'japanese no vacancy', 'kanji'],
    ['🈹', 'japanese discount', 'kanji'],
    ['🈲', 'japanese prohibited', 'kanji'],
    ['🅰️', 'a button', 'blood'],
    ['🅱️', 'b button', 'blood'],
    ['🆎', 'ab button', 'blood'],
    ['🆑', 'cl button', 'clear'],
    ['🅾️', 'o button', 'blood'],
    ['🆘', 'sos button', 'help'],
    ['❌', 'cross mark', 'no x'],
    ['⭕', 'hollow red circle', 'o'],
    ['🛑', 'stop sign', 'stop'],
    ['⛔', 'no entry', 'stop'],
    ['📛', 'name badge', 'name'],
    ['🚫', 'prohibited', 'ban'],
    ['💯', 'hundred points', '100'],
    ['💢', 'anger symbol', 'mad'],
    ['♨️', 'hot springs', 'onsen'],
    ['🚷', 'no pedestrians', 'ban'],
    ['🚯', 'no littering', 'ban'],
    ['🚳', 'no bicycles', 'ban'],
    ['🚱', 'non-potable water', 'ban'],
    ['🔞', 'no one under eighteen', 'nsfw'],
    ['📵', 'no mobile phones', 'ban'],
    ['🚭', 'no smoking', 'ban'],
    ['❗', 'exclamation mark', 'alert'],
    ['❕', 'white exclamation mark', 'alert'],
    ['❓', 'question mark', 'help'],
    ['❔', 'white question mark', 'help'],
    ['‼️', 'double exclamation mark', 'wow'],
    ['⁉️', 'exclamation question mark', 'what'],
    ['🔅', 'dim button', 'brightness'],
    ['🔆', 'bright button', 'brightness'],
    ['〽️', 'part alternation mark', 'mark'],
    ['⚠️', 'warning', 'caution'],
    ['🚸', 'children crossing', 'school'],
    ['🔱', 'trident emblem', 'emblem'],
    ['⚜️', 'fleur-de-lis', 'emblem'],
    ['🔰', 'japanese symbol for beginner', 'new'],
    ['♻️', 'recycling symbol', 'recycle'],
    ['✅', 'check mark button', 'done'],
    ['🈯', 'japanese reserved button', 'kanji'],
    ['💹', 'chart increasing with yen', 'stocks'],
    ['❇️', 'sparkle', 'shine'],
    ['✳️', 'eight-spoked asterisk', 'star'],
    ['❎', 'cross mark button', 'no'],
    ['🌐', 'globe with meridians', 'www'],
    ['💠', 'diamond with a dot', 'jewel'],
    ['Ⓜ️', 'circled m', 'metro'],
    ['🌀', 'cyclone', 'swirl'],
    ['💤', 'zzz', 'sleep'],
    ['🏧', 'atm sign', 'bank'],
    ['🚾', 'water closet', 'restroom'],
    ['♿', 'wheelchair symbol', 'access'],
    ['🅿️', 'p button', 'parking'],
    ['🛗', 'elevator', 'lift'],
    ['🛂', 'passport control', 'travel'],
    ['🛃', 'customs', 'travel'],
    ['🛄', 'baggage claim', 'travel'],
    ['🛅', 'left luggage', 'travel'],
    ['🚹', 'men’s room', 'restroom'],
    ['🚺', 'women’s room', 'restroom'],
    ['🚼', 'baby symbol', 'nursery'],
    ['⚧️', 'transgender symbol', 'pride'],
    ['🚻', 'restroom', 'wc'],
    ['🚮', 'litter in bin sign', 'trash'],
    ['🎦', 'cinema', 'movie'],
    ['📶', 'antenna bars', 'signal'],
    ['🈁', 'japanese here button', 'kanji'],
    ['🔣', 'input symbols', 'symbols'],
    ['ℹ️', 'information', 'info'],
    ['🔤', 'input latin letters', 'abc'],
    ['🔡', 'input latin lowercase', 'abcd'],
    ['🔠', 'input latin uppercase', 'abcd'],
    ['🆖', 'ng button', 'no good'],
    ['🆗', 'ok button', 'ok'],
    ['🆙', 'up! button', 'up'],
    ['🆒', 'cool button', 'cool'],
    ['🆕', 'new button', 'new'],
    ['🆓', 'free button', 'free'],
    ['0️⃣', 'keycap 0', 'zero'],
    ['1️⃣', 'keycap 1', 'one'],
    ['2️⃣', 'keycap 2', 'two'],
    ['3️⃣', 'keycap 3', 'three'],
    ['4️⃣', 'keycap 4', 'four'],
    ['5️⃣', 'keycap 5', 'five'],
    ['6️⃣', 'keycap 6', 'six'],
    ['7️⃣', 'keycap 7', 'seven'],
    ['8️⃣', 'keycap 8', 'eight'],
    ['9️⃣', 'keycap 9', 'nine'],
    ['🔟', 'keycap 10', 'ten'],
    ['🔢', 'input numbers', '123'],
    ['#️⃣', 'keycap #', 'hash'],
    ['*️⃣', 'keycap *', 'star'],
    ['⏏️', 'eject button', 'eject'],
    ['▶️', 'play button', 'play'],
    ['⏸️', 'pause button', 'pause'],
    ['⏯️', 'play or pause button', 'media'],
    ['⏹️', 'stop button', 'stop'],
    ['⏺️', 'record button', 'rec'],
    ['⏭️', 'next track button', 'next'],
    ['⏮️', 'last track button', 'prev'],
    ['⏩', 'fast-forward button', 'ff'],
    ['⏪', 'fast reverse button', 'rewind'],
    ['⏫', 'fast up button', 'up'],
    ['⏬', 'fast down button', 'down'],
    ['◀️', 'reverse button', 'back'],
    ['🔼', 'upwards button', 'up'],
    ['🔽', 'downwards button', 'down'],
    ['➡️', 'right arrow', 'next'],
    ['⬅️', 'left arrow', 'back'],
    ['⬆️', 'up arrow', 'up'],
    ['⬇️', 'down arrow', 'down'],
    ['↗️', 'up-right arrow', 'diag'],
    ['↘️', 'down-right arrow', 'diag'],
    ['↙️', 'down-left arrow', 'diag'],
    ['↖️', 'up-left arrow', 'diag'],
    ['↕️', 'up-down arrow', 'swap'],
    ['↔️', 'left-right arrow', 'swap'],
    ['↩️', 'right arrow curving left', 'return'],
    ['↪️', 'left arrow curving right', 'forward'],
    ['⤴️', 'right arrow curving up', 'up'],
    ['⤵️', 'right arrow curving down', 'down'],
    ['🔀', 'shuffle tracks button', 'shuffle'],
    ['🔁', 'repeat button', 'loop'],
    ['🔂', 'repeat single button', 'loop'],
    ['🔄', 'counterclockwise arrows', 'refresh'],
    ['🔃', 'clockwise vertical arrows', 'reload'],
    ['🎵', 'musical note', 'music'],
    ['🎶', 'musical notes', 'music'],
    ['➕', 'plus', 'add'],
    ['➖', 'minus', 'subtract'],
    ['➗', 'divide', 'math'],
    ['✖️', 'multiply', 'math'],
    ['♾️', 'infinity', 'forever'],
    ['💲', 'heavy dollar sign', 'money'],
    ['💱', 'currency exchange', 'money'],
    ['™️', 'trade mark', 'tm'],
    ['©️', 'copyright', 'legal'],
    ['®️', 'registered', 'legal'],
    ['〰️', 'wavy dash', 'wave'],
    ['➰', 'curly loop', 'loop'],
    ['➿', 'double curly loop', 'loop'],
    ['🔚', 'end arrow', 'end'],
    ['🔙', 'back arrow', 'back'],
    ['🔛', 'on! arrow', 'on'],
    ['🔝', 'top arrow', 'top'],
    ['🔜', 'soon arrow', 'soon'],
    ['✔️', 'check mark', 'done'],
    ['☑️', 'check box with check', 'done'],
    ['🔘', 'radio button', 'select'],
    ['🔴', 'red circle', 'dot'],
    ['🟠', 'orange circle', 'dot'],
    ['🟡', 'yellow circle', 'dot'],
    ['🟢', 'green circle', 'dot'],
    ['🔵', 'blue circle', 'dot'],
    ['🟣', 'purple circle', 'dot'],
    ['⚫', 'black circle', 'dot'],
    ['⚪', 'white circle', 'dot'],
    ['🟤', 'brown circle', 'dot'],
    ['🔺', 'red triangle pointed up', 'up'],
    ['🔻', 'red triangle pointed down', 'down'],
    ['🔸', 'small orange diamond', 'shape'],
    ['🔹', 'small blue diamond', 'shape'],
    ['🔶', 'large orange diamond', 'shape'],
    ['🔷', 'large blue diamond', 'shape'],
    ['🔳', 'white square button', 'button'],
    ['🔲', 'black square button', 'button'],
    ['▪️', 'black small square', 'shape'],
    ['▫️', 'white small square', 'shape'],
    ['◾', 'black medium-small square', 'shape'],
    ['◽', 'white medium-small square', 'shape'],
    ['◼️', 'black medium square', 'shape'],
    ['◻️', 'white medium square', 'shape'],
    ['🟥', 'red square', 'shape'],
    ['🟧', 'orange square', 'shape'],
    ['🟨', 'yellow square', 'shape'],
    ['🟩', 'green square', 'shape'],
    ['🟦', 'blue square', 'shape'],
    ['🟪', 'purple square', 'shape'],
    ['⬛', 'black large square', 'shape'],
    ['⬜', 'white large square', 'shape'],
    ['🟫', 'brown square', 'shape'],
    ['🔈', 'speaker low volume', 'sound'],
    ['⭐', 'star', 'favorite'],
    ['🌟', 'glowing star', 'shine'],
    ['✨', 'sparkles', 'magic'],
    ['⚡', 'high voltage', 'zap'],
    ['🔥', 'fire', 'lit'],
    ['💥', 'collision', 'boom'],
    ['💫', 'dizzy', 'stars'],
    ['💨', 'dashing away', 'fast'],
    ['💦', 'sweat droplets', 'water'],
    ['💤', 'zzz', 'sleep'],
  ],
  flags: [
    ['🏁', 'chequered flag', 'race'],
    ['🚩', 'triangular flag', 'mark'],
    ['🎌', 'crossed flags', 'japan'],
    ['🏴', 'black flag', 'pirate'],
    ['🏳️', 'white flag', 'surrender'],
    ['🏳️‍🌈', 'rainbow flag', 'pride'],
    ['🏳️‍⚧️', 'transgender flag', 'pride'],
    ['🏴‍☠️', 'pirate flag', 'jolly roger'],
    ['🇺🇳', 'flag united nations', 'un'],
    ['🇺🇸', 'flag united states', 'usa america'],
    ['🇬🇧', 'flag united kingdom', 'uk britain'],
    ['🇨🇦', 'flag canada', 'canada'],
    ['🇦🇺', 'flag australia', 'australia'],
    ['🇳🇿', 'flag new zealand', 'nz'],
    ['🇩🇪', 'flag germany', 'germany'],
    ['🇫🇷', 'flag france', 'france'],
    ['🇮🇹', 'flag italy', 'italy'],
    ['🇪🇸', 'flag spain', 'spain'],
    ['🇵🇹', 'flag portugal', 'portugal'],
    ['🇳🇱', 'flag netherlands', 'holland'],
    ['🇧🇪', 'flag belgium', 'belgium'],
    ['🇨🇭', 'flag switzerland', 'swiss'],
    ['🇦🇹', 'flag austria', 'austria'],
    ['🇸🇪', 'flag sweden', 'sweden'],
    ['🇳🇴', 'flag norway', 'norway'],
    ['🇩🇰', 'flag denmark', 'denmark'],
    ['🇫🇮', 'flag finland', 'finland'],
    ['🇮🇪', 'flag ireland', 'ireland'],
    ['🇵🇱', 'flag poland', 'poland'],
    ['🇨🇿', 'flag czechia', 'czech'],
    ['🇭🇺', 'flag hungary', 'hungary'],
    ['🇬🇷', 'flag greece', 'greece'],
    ['🇹🇷', 'flag turkey', 'turkey'],
    ['🇺🇦', 'flag ukraine', 'ukraine'],
    ['🇷🇺', 'flag russia', 'russia'],
    ['🇯🇵', 'flag japan', 'japan'],
    ['🇰🇷', 'flag south korea', 'korea'],
    ['🇨🇳', 'flag china', 'china'],
    ['🇮🇳', 'flag india', 'india'],
    ['🇵🇰', 'flag pakistan', 'pakistan'],
    ['🇧🇩', 'flag bangladesh', 'bangladesh'],
    ['🇮🇩', 'flag indonesia', 'indonesia'],
    ['🇹🇭', 'flag thailand', 'thailand'],
    ['🇻🇳', 'flag vietnam', 'vietnam'],
    ['🇵🇭', 'flag philippines', 'philippines'],
    ['🇲🇾', 'flag malaysia', 'malaysia'],
    ['🇸🇬', 'flag singapore', 'singapore'],
    ['🇹🇼', 'flag taiwan', 'taiwan'],
    ['🇭🇰', 'flag hong kong', 'hongkong'],
    ['🇲🇽', 'flag mexico', 'mexico'],
    ['🇧🇷', 'flag brazil', 'brazil'],
    ['🇦🇷', 'flag argentina', 'argentina'],
    ['🇨🇱', 'flag chile', 'chile'],
    ['🇨🇴', 'flag colombia', 'colombia'],
    ['🇵🇪', 'flag peru', 'peru'],
    ['🇿🇦', 'flag south africa', 'south africa'],
    ['🇪🇬', 'flag egypt', 'egypt'],
    ['🇳🇬', 'flag nigeria', 'nigeria'],
    ['🇰🇪', 'flag kenya', 'kenya'],
    ['🇲🇦', 'flag saudi arabia', 'saudi'],
    ['🇦🇪', 'flag united arab emirates', 'uae'],
    ['🇮🇱', 'flag israel', 'israel'],
    ['🇮🇷', 'flag iran', 'iran'],
    ['🇮🇶', 'flag iraq', 'iraq'],
  ],
};

const toItem = (
  category: TEmojiCategoryId,
  [emoji, name, keywords]: TEmojiSeed,
): TEmojiItem => ({
  emoji,
  name,
  keywords: keywords?.split(' ') ?? [],
  category,
});

export const EMOJIS: TEmojiItem[] = EMOJI_CATEGORIES.flatMap((category) =>
  seeds[category.id].map((seed) => toItem(category.id, seed)),
);

export const filterEmojis = (
  emojis: TEmojiItem[],
  query: string,
  category?: TEmojiCategoryId,
) => {
  const normalized = query.trim().toLowerCase();

  return emojis.filter((item) => {
    if (normalized.length === 0 && category != null && item.category !== category) {
      return false;
    }

    if (normalized.length === 0) {
      return true;
    }

    if (item.emoji.includes(normalized)) {
      return true;
    }

    if (item.name.includes(normalized)) {
      return true;
    }

    return item.keywords.some((keyword) => keyword.includes(normalized));
  });
};
