import {
  createFileTreeCollection,
  createTreeCollection,
  TreeCollection,
  type FilePathTreeNode,
  type TreeCollectionOptions,
  type TreeNode,
} from './collection';
import { treeViewClasses } from './classes';
import { useTreeViewContext, useTreeViewNodeContext } from './context';
import {
  TreeViewBranch,
  TreeViewBranchContent,
  TreeViewBranchControl,
  TreeViewBranchIndentGuide,
  TreeViewBranchIndicator,
  TreeViewBranchText,
  TreeViewBranchTrigger,
  TreeViewContextRender,
  TreeViewItem,
  TreeViewItemIndicator,
  TreeViewItemText,
  TreeViewLabel,
  TreeViewNodeCheckbox,
  TreeViewNodeContextRender,
  TreeViewNodeProvider,
  TreeViewNodeRenameInput,
  TreeViewRoot,
  TreeViewRootProvider,
  TreeViewTree,
} from './parts';
import { TreeViewNode } from './tree-view-node';
import type {
  TTreeViewBranchContentProps,
  TTreeViewBranchControlProps,
  TTreeViewBranchIndicatorProps,
  TTreeViewBranchProps,
  TTreeViewBranchTextProps,
  TTreeViewBranchTriggerProps,
  TTreeViewExpandedChangeDetails,
  TTreeViewFocusChangeDetails,
  TTreeViewItemIndicatorProps,
  TTreeViewItemProps,
  TTreeViewItemTextProps,
  TTreeViewLabelProps,
  TTreeViewNodeProps,
  TTreeViewNodeProviderProps,
  TTreeViewNodeRenderProps,
  TTreeViewNodeState,
  TTreeViewRootProps,
  TTreeViewRootProviderProps,
  TTreeViewSelectionChangeDetails,
  TTreeViewSize,
  TTreeViewTreeProps,
  TTreeViewVariant,
  TUseTreeViewProps,
  TUseTreeViewReturn,
} from './types';
import { useTreeView } from './use-tree-view';

export const TreeView = {
  Root: TreeViewRoot,
  RootProvider: TreeViewRootProvider,
  Tree: TreeViewTree,
  Label: TreeViewLabel,
  Branch: TreeViewBranch,
  BranchContent: TreeViewBranchContent,
  BranchControl: TreeViewBranchControl,
  BranchIndentGuide: TreeViewBranchIndentGuide,
  BranchIndicator: TreeViewBranchIndicator,
  BranchText: TreeViewBranchText,
  BranchTrigger: TreeViewBranchTrigger,
  Item: TreeViewItem,
  ItemText: TreeViewItemText,
  ItemIndicator: TreeViewItemIndicator,
  NodeProvider: TreeViewNodeProvider,
  NodeContext: TreeViewNodeContextRender,
  Node: TreeViewNode,
  NodeCheckbox: TreeViewNodeCheckbox,
  NodeRenameInput: TreeViewNodeRenameInput,
  Context: TreeViewContextRender,
};

export type {
  TTreeViewRootProps,
  TTreeViewRootProviderProps,
  TTreeViewNodeProps,
  TTreeViewNodeRenderProps,
  TTreeViewNodeProviderProps,
  TTreeViewSize,
  TTreeViewVariant,
  TTreeViewNodeState,
  TTreeViewSelectionChangeDetails,
  TTreeViewExpandedChangeDetails,
  TTreeViewFocusChangeDetails,
  TTreeViewBranchProps,
  TTreeViewBranchContentProps,
  TTreeViewBranchControlProps,
  TTreeViewBranchIndicatorProps,
  TTreeViewBranchTextProps,
  TTreeViewBranchTriggerProps,
  TTreeViewItemProps,
  TTreeViewItemTextProps,
  TTreeViewItemIndicatorProps,
  TTreeViewLabelProps,
  TTreeViewTreeProps,
  TUseTreeViewProps,
  TUseTreeViewReturn,
  TreeCollection,
  TreeCollectionOptions,
  TreeNode,
  FilePathTreeNode,
};

export type UseTreeViewProps<T extends TreeNode = TreeNode> = TUseTreeViewProps<T>;
export type UseTreeViewReturn<T extends TreeNode = TreeNode> = TUseTreeViewReturn<T>;
export type TreeViewSelectionChangeDetails = TTreeViewSelectionChangeDetails;
export type TreeViewExpandedChangeDetails = TTreeViewExpandedChangeDetails;
export type TreeViewNodeState = TTreeViewNodeState;

export {
  TreeViewRoot,
  TreeViewRootProvider,
  TreeViewTree,
  TreeViewLabel,
  TreeViewBranch,
  TreeViewBranchContent,
  TreeViewBranchControl,
  TreeViewBranchIndentGuide,
  TreeViewBranchIndicator,
  TreeViewBranchText,
  TreeViewBranchTrigger,
  TreeViewItem,
  TreeViewItemText,
  TreeViewItemIndicator,
  TreeViewNode,
  TreeViewNodeCheckbox,
  TreeViewNodeRenameInput,
  TreeViewNodeProvider,
  createTreeCollection,
  createFileTreeCollection,
  useTreeView,
  useTreeViewContext,
  useTreeViewNodeContext,
  treeViewClasses,
};

export default TreeView;
